apiVersion: v1
kind: Secret

metadata:
  name: gateway-env
  namespace: qubide-main
type: Opaque
stringData:
  NODE_ENV: "production"
  MINIO_ENDPOINT: minio.minio-dev.svc.cluster.local
  MINIO_ACCESS_KEY: secret
  MINIO_SECRET_KEY: very_secret
  MINIO_PORT: "9000"
  DATABASE_URL: postgresql://postgres:pgsql@localhost:5432/qubideDb
  REDIS_URL: redis://localhost:6379
  ACCESS_TOKEN_SECRET: very_secret
  ACCESS_TOKEN_EXPIRATION_SEC: "300"
  REFRESH_TOKEN_SECRET: very_secret
  REFRESH_TOKEN_EXPIRATION_SEC: "86400"
  COOKIE_SECRET: very_secret
  EMAIL_VERIFICATION_SECRET: very_secret
  EMAIL_VERIFICATION_EXPIRATION_SEC: "300"
  FORGOT_PASSWORD_SECRET: very_secret
  FORGOT_PASSWORD_EXPIRATION_SEC: "300"
  SUDO_ACCESS_TOKEN_SECRET: very_secret
  SUDO_ACCESS_TOKEN_EXPIRATION_SEC: "300"
  TWOFACTOR_VERIFICATION_SECRET: very_secret
  TWOFACTOR_VERIFICATION_EXPIRATION_SEC: "300"
  INVITATION_SECRET: very_secret
  INVITATION_EXPIRATION_SEC: "300"
  CLIENT_URL: "http://localhost:3000"
  CLIENT_DOMAIN: "qubide.cloud"
  BACKEND_URL: "http://localhost:3002"
  AES_KEY: very_secret
  AES_IV: very_secret
  RESEND_API_KEY: very_secret