apiVersion: v1
kind: Secret

metadata:
  name: gateway-env
  namespace: qubide-main
type: Opaque
stringData:
  MINIO_ACCESS_KEY: secret
  MINIO_SECRET_KEY: very_secret
  ACCESS_TOKEN_SECRET: very_secret
  ACCESS_TOKEN_EXPIRATION_SEC: "300"
  DATABASE_URL: postgresql://postgres:pgsql@localhost:5432/qubideDb
  REDIS_URL: redis://localhost:6379
  ACCESS_TOKEN_SECRET: very_secret
  REFRESH_TOKEN_SECRET: very_secret
  COOKIE_SECRET: very_secret
  EMAIL_VERIFICATION_SECRET: very_secret
  FORGOT_PASSWORD_SECRET: very_secret
  SUDO_ACCESS_TOKEN_SECRET: very_secret
  TWOFACTOR_VERIFICATION_SECRET: very_secret
  AES_KEY: very_secret
  AES_IV: very_secret
  MAIL_OUTGOING_SERVER: secret
  MAIL_SMTP_PORT: "587"
  MAIL_USERNAME: secret
  MAIL_PASSWORD: very_secret