apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  # ClusterIssuer (your letsencrypt‑prod) lives at the cluster level, so you never specify a namespace
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: prakashbanjade191@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
