apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-sa
  namespace: qubide
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-delete-role
  namespace: qubide
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["delete", "get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["delete", "get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["delete", "get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-delete-binding
  namespace: qubide
subjects:
  - kind: ServiceAccount
    name: runner-sa
    namespace: qubide
roleRef:
  kind: Role
  name: runner-delete-role
  apiGroup: rbac.authorization.k8s.io
