apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  namespace: qubide
  labels:
    app: service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_name
  template:
    metadata:
      namespace: qubide
      labels:
        app: service_name
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      initContainers:
        - name: copy-minio-resources
          image: minio/mc
          command: ["sh", "-c"]
          args:
            - |
              set -e
              mc alias set minio http://minio.minio-dev.svc.cluster.local:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" && mc cp --recursive minio/cloud-ide/code/service_name/ /workspace/
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: runner-env
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: runner-env
                  key: MINIO_SECRET_KEY
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
      serviceAccountName: runner-sa
      containers:
        - name: runner
          image: prakashbanjade/cloud-ide-runner:v1.1
          imagePullPolicy: Always
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: runner-env
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: runner-env
                  key: MINIO_SECRET_KEY
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: runner-env
                  key: ACCESS_TOKEN_SECRET
            - name: ACCESS_TOKEN_EXPIRATION_SEC
              valueFrom:
                secretKeyRef:
                  name: runner-env
                  key: ACCESS_TOKEN_EXPIRATION_SEC
            - name: MINIO_ENDPOINT
              value: minio.minio-dev.svc.cluster.local
            - name: MINIO_PORT
              value: "9000"
            - name: REPL_ID
              value: "service_name"
          ports:
            - containerPort: 3003 # expose ws port
            - containerPort: LANG_PORT # expose the port where the application might run on. eg: a node app running on port 3000
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            requests:
              cpu: "300m"       # 0.3 core
              memory: "512Mi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "1"          # 1 full core
              memory: "1Gi"
              ephemeral-storage: "5Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: service_name
  namespace: qubide
spec:
  selector:
    app: service_name
  ports:
    - protocol: TCP
      name: ws
      port: 3003
      targetPort: 3003
    - protocol: TCP
      name: user
      port: LANG_PORT
      targetPort: LANG_PORT
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service_name
  namespace: qubide
spec:
  ingressClassName: nginx
  rules:
    - host: service_name.prakashbanjade.com # ws endpoint
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service_name
                port:
                  number: 3003
    - host: service_name.qubide.cloud # node/python app endpoint
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service_name
                port:
                  number: LANG_PORT
