apiVersion: v1
kind: Secret

metadata:
  name: runner-env
  namespace: qubide
type: Opaque
stringData:
  MINIO_ACCESS_KEY: secret
  MINIO_SECRET_KEY: very_secret
  ACCESS_TOKEN_SECRET: very_secret
  ACCESS_TOKEN_EXPIRATION_SEC: "300"